From python 
RUN pip3 install flask 
COPY ./static /home/Tatbegi/static/
COPY ./templates /home/Tatbegi/templates/
COPY sample-app.py /home/Tatbegi/
EXPOSE 8080
CMD python3 /home/Tatbegi/sample-app.py
